### ISSUE TITLE
Provide Docker/Gitpod based tools to run our code

### ISSUE THREAD

**Issue by giuliavezzani** [robotology/GRASPA-benchmark#9]
We need to use `gitpod` and create the `docker` image to simplify the reproduction of our scripts.

**Comment by pattacini** [comment]
The Gitpod infrastructure is basically ready ✨ 

You can visit the repository home page and click on the Gitpod green button on top-right corner (if you have the Chrome extension) or just click on https://gitpod.io/#https://github.com/robotology/GRASPA-benchmark. You may want to hide this URL behind the following button that we can embed in the main `READM.md` to help users w/o the plugin launch the environment:

[![Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://gitpod.io/#https://github.com/robotology/GRASPA-benchmark)

After a few instants, Gitpod will load the Docker image and create the workspace. This workspace comes with all the required dependencies installed plus the repo already cloned so that what's left is to build `GRASPA-benchmark`:
```sh
$ mkdir build && cd build && cmake && make -j4
```

We might consider bundling these commands into a `build.sh` (remember to make it executable) that we can commit to the root level of this repo to ease building.

Here come some sore points 😞 

**I think that Simox has a flaw** so that when we try building our binaries we end up having some configuration problems related to missing `Qt5::GUI` and `Qt5::OpenGL` that actually we don't need! As a result, if you configure `GRASPA-benchmark` through `ccmake` you'll be prompted with those errors. Otherwise, just rely on `cmake` and proceed forward: the build will be successful anyway.

To fix this goof, we could just add up the following line to our main `CMakeLists.txt`:
```cmake
find_package(Qt5 5.5.0 COMPONENTS OpenGL Core Gui Designer)
```
As said, it's not necessary but helps things go smoothly.

If you need to open X11 in Gitpod, click on the `Ports` status bar (bottom-right corner), and open the `6080` port; you'll be automagically redirected to X11.

So far I'using my [dockerfiles repo][1] and my [dockerhub][2]. Thus, I warmly recommend @fbottarel switch to his own. Once done, just edit the file [.gitpod.yml][3] located here in to make it point to the new docker container.

⚠️ I'm currently regenerating the docker container, so please wait a bit until it'll be ready.

[1]: https://github.com/pattacini/technical-evaluation
[2]: https://cloud.docker.com/u/pattacini/repository/docker/pattacini/graspa-benchmark
[3]: ../blob/master/.gitpod.yml

**Comment by pattacini** [comment]
The docker image is available 🐳

**Comment by fbottarel** [comment]
Thanks for taking care of this. I will take over with my own docker image after submission (and some vacation...), since I think I might have messed it up while trying to obtain the graphical output.

**Comment by pattacini** [comment]
You can copy out exactly this [Docker file][1], no need for starting from scratch. Then, you can elaborate on this baseline, if you need customizations.

[1]: https://github.com/pattacini/dockerfiles/blob/master/GRASPA-benchmark/Dockerfile

**Comment by pattacini** [comment]
Python packages are now installed for `gitpod` user. See https://github.com/pattacini/dockerfiles/commit/6a505aeda2e4812d49c2189c13cd8f8e152f9456.

cc @giuliavezzani

**Comment by pattacini** [comment]
@giuliavezzani 
From within Gitpod, if you launch `pip3 freeze`, you'll get:
```
numpy==1.17.0
numpy-stl==2.10.1
opencv-contrib-python==4.1.0.25
opencv-python==4.1.0.25
python-utils==2.3.0
scipy==1.3.0
six==1.12.0
```
meaning that we should be ok with python packages installation.

@fbottarel 
As I was having many troubles while compiling `simox/master` because of the new C++20 features maintainers are pushing, I've switched to the use of [`simox/v2.3.74`][1] (4 months old) with good results.

[1]: https://gitlab.com/Simox/simox/-/tags/v2.3.74

**Comment by giuliavezzani** [comment]
@pattacini I've tested the python scripts. As long as they are launched using `python3` as interpreter, they work.

**Comment by pattacini** [comment]
This change https://github.com/pattacini/dockerfiles/commit/82bc0c4115312d76cbae35e24782df0f6d48a704 will make the default python interpreter be the `3.6`.

🏗 Rebuilding the container 🐳

**Comment by pattacini** [comment]
@giuliavezzani the new container now aliases `python3.6` as `python`.

**Comment by fbottarel** [comment]
I am building and pushing my own docker images/containers for the benchmark. Since the GitPod image and the "docker-pulled" image must be different, I have decided to go for 2 different builds:
- one image will be made for GitPod integration, and right now has the priority
- the second one will be made to be pulled on the user's machine via docker. 

Both images will contain environments ready to test the benchmark. 
[Here](https://hub.docker.com/r/fbottarel/graspa-benchmark) you can find the repo containing both (I will make sure to provide indicative tags for both). I have set up DockerHub to automatically build images from [my dockerfiles] whenever there is a push on the GitHub repo. 

I will edit the .gitpod.yml file as soon as image upload is completed.

**Comment by fbottarel** [comment]
GitPod environment is ready and online.
